-- MySQL Script generated by MySQL Workbench
-- Fri Feb 12 18:08:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema newsagent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newsagent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newsagent` DEFAULT CHARACTER SET utf8 ;
USE `newsagent` ;

-- -----------------------------------------------------
-- Table `newsagent`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsagent`.`resource` ;

CREATE TABLE IF NOT EXISTS `newsagent`.`resource` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newsagent`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsagent`.`role` ;

CREATE TABLE IF NOT EXISTS `newsagent`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newsagent`.`role_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsagent`.`role_resource` ;

CREATE TABLE IF NOT EXISTS `newsagent`.`role_resource` (
  `role_id` INT NOT NULL,
  `resource_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `resource_id`),
  INDEX `fk_role_has_resource_resource1_idx` (`resource_id` ASC) VISIBLE,
  INDEX `fk_role_has_resource_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_resource_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `newsagent`.`resource` (`id`),
  CONSTRAINT `fk_role_has_resource_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `newsagent`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newsagent`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsagent`.`user` ;

CREATE TABLE IF NOT EXISTS `newsagent`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newsagent`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `newsagent`.`user_role` ;

CREATE TABLE IF NOT EXISTS `newsagent`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_has_role_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `newsagent`.`role` (`id`),
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `newsagent`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
